# <span style="color:red"> QTM 151 - Practice Quiz </span>

<font size = 5>

**Submit as an HTML file** (see images below)

<font size = 3>

Step 1: Click the 3 dots in the toolbar for "More Actions"

<img src="practice_quiz_figures/step1.png" alt="drawing" width = "600"/>

***
Step 2: Choose "export"

<img src="practice_quiz_figures/step2.png" alt="drawing" width = "600"/>

***
Step 3: Select "HTML" from the dropdown window

<img src="practice_quiz_figures/step3.png" alt="drawing" width = "600"/>

***
Step 4: Select "Export" in the pop-up window.

<img src="practice_quiz_figures/step4.png" alt="drawing" width = "300"/>

Upload the .html file as your submission

<font size="5"> 

Print your name below

In [22]:
# Write your answer here

print( )

<font size = "5" >
This quiz is open book 

- You can use the lecture notes
- You will get partial credit for attempting the questions
- To get full credit, the code should work as intended
- You should <span style="color:red"> NOT </span> communicate with other students

Print the following message: <br>

"I will abide by Emory's code of conduct"

In [23]:
# Write your answer here:
print( )

<font size = "5">

Import pandas

In [24]:
import pandas as pd
import numpy as np

(1) Replace the values of a column

Consider the DataFrame df_books created below.
In the "language" column, change the values "Eng" and "Jap" to "English" and "Japanese" respectively.

Do this by using the .replace() method.

In [35]:
# Create example DataFrame
titles = ["Kafka on the Shore", "Norwegian Wood", "1984", "Animal Farm", "The Wind-Up Bird Chronicle"]
languages = ["Jap", "Jap", "Eng", "Eng", "Jap"]
years = [2002, 1987, 1949, 1945, 1994]

book_dict = {"title": titles, "language": languages, "year": years}
df_books = pd.DataFrame(book_dict)

# Write your answer here:
df_books["languages"] = df_books["language"].replace({"Jap": "Japanese", "Eng": "English"})
df_books

                        title language  year languages
0          Kafka on the Shore      Jap  2002  Japanese
1              Norwegian Wood      Jap  1987  Japanese
2                        1984      Eng  1949   English
3                 Animal Farm      Eng  1945   English
4  The Wind-Up Bird Chronicle      Jap  1994  Japanese

<font size = "5">

(2) Recode a numeric column

<font size = "3">

- Consider the DataFrame ``df_books`` created above
- Recode the "year" column into a new column "year_brackets" <br>
with the following categories:

$\qquad$ ``` ["Before 1950", "1950–1999", "2000 onwards"] ```

$\qquad$ HINT: Use the "pd.cut()" command.

In [26]:
# your code here


df_books["year_category"] = pd.cut(df_books["year"],
                            bins = [float("-inf"), 1950, 1999, float("inf")],
                            right = True,
                            labels = ["Before 1950", "1950–1999", "2000 onwards"])
df_books

#circuits["hemisphere"] = pd.cut(circuits["lat"], 
                    #            bins = lat_bins,
                      #          right = True,
                     #           labels = lat_labels)

                        title language  year languages year_category
0          Kafka on the Shore      Jap  2002  Japanese  2000 onwards
1              Norwegian Wood      Jap  1987  Japanese     1950–1999
2                        1984      Eng  1949   English   Before 1950
3                 Animal Farm      Eng  1945   English   Before 1950
4  The Wind-Up Bird Chronicle      Jap  1994  Japanese     1950–1999

<font size = "5">

(3) Rename column

<font size = "3">

- Consider the DataFrame ``df_movies`` created above
- Rename the column "runtime" to "runtime(minutes)"

In [27]:
# Write your answer here:
#circuits = circuits.rename(columns={'Uniform Resource Locator': 'url'})

df_books = df_books.rename(columns={"year" : "publication_year"})
df_books

,title,language,publication_year,languages,year_category
0,Kafka on the Shore,Jap,2002,Japanese,2000 onwards
1,Norwegian Wood,Jap,1987,Japanese,1950–1999
2,1984,Eng,1949,English,Before 1950
3,Animal Farm,Eng,1945,English,Before 1950
4,The Wind-Up Bird Chronicle,Jap,1994,Japanese,1950–1999

<font size = "5">

(4) Merge dataset

<font size = "3">

- Consider the DataFrames ``df_movies`` (created above) and ``df_scores`` (created below)
- Create a new dataset using  ```pd.merge()``` using <br>
"df_movies" as the primary dataset, and <br>
"df_scores" as the secondary dataset, merging on <br>
the column "title"
- You should **ONLY** merge the "imdb_score" column <br>
from the secondary dataset (not the "director" column)

HINT: Use ```[[...]]``` to extract a subset of columns <br>
from the secondary dataset before merging

In [28]:
# Create example DataFrame
ratings = [8.7, 8.5, 9.1, 8.9, 8.6]
authors = ["Haruki Murakami", "Haruki Murakami", "George Orwell", "George Orwell", "Haruki Murakami"]

df_ratings = pd.DataFrame({
    "title": titles,
    "rating": ratings,
    "author": authors
})

# Write your answer here:
df_merged = pd.merge(df_books,
                     df_ratings[["title", "rating"]],
                     on = "title",
                     how = "left")
df_merged

,title,language,publication_year,languages,year_category,rating
0,Kafka on the Shore,Jap,2002,Japanese,2000 onwards,8.7
1,Norwegian Wood,Jap,1987,Japanese,1950–1999,8.5
2,1984,Eng,1949,English,Before 1950,9.1
3,Animal Farm,Eng,1945,English,Before 1950,8.9
4,The Wind-Up Bird Chronicle,Jap,1994,Japanese,1950–1999,8.6

(5) Aggregate and sort

Using the merged dataset you created above, do the following in a single line by chaining:

Group the dataset by "language"

Aggregate the following statistics: average rating, maximum rating, minimum rating

Sort by average rating in descending order

Print the resulting DataFrame.

In [31]:
# Write your answer here:
#example_3 = df_example.agg(my_x = ('A', 'max'),
                          # y = ('B', 'min'),
                        #   z = ('C', 'mean'))
agg = df_merged.groupby("languages").agg(avg = ('rating', 'mean'),
                                        max = ('rating', 'max'),
                                        min = ('rating', 'min'))

agg

           avg  max  min
languages
English    9.0  9.1  8.9
Japanese   8.6  8.7  8.5

<font size = "5">

(6) Query and Aggregate

<font size = "3">

(6) Query and extract

Using the merged dataset you created above, do the following in a single line by chaining:

Subset the observations for "language == 'Japanese'" using .query()

Sort the values by "publication_year" (oldest first)

Extract the two oldest books

Print the resulting DataFrame.

In [33]:
# Write your answer here:
df_merged.query("languages == 'Japanese'").sort_values(by = "publication_year", ascending = True).iloc[0:2,:]

,title,language,publication_year,languages,year_category,rating
1,Norwegian Wood,Jap,1987,Japanese,1950–1999,8.5
4,The Wind-Up Bird Chronicle,Jap,1994,Japanese,1950–1999,8.6